base/base/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bulletin/', include('bulletin.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('bulletin:index')))
]

base/bulletin/urls.py
from django.urls import path
from django.contrib.auth import views as av

from bulletin import views as bv

app_name = 'bulletin'
urlpatterns = [
    path('', bv.IndexView.as_view(), name='index'),
    path(
        'login/',
        av.LoginView.as_view(
            template_name='bulletin/login.html',
            extra_context={'no_nav': True},
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path('logout/', av.LogoutView.as_view(), name='logout'),
    path(
        'password/change/',
        bv.PasswordUpdateView.as_view(),
        name='change_password'
    ),
    path(
        'register/',
        bv.UserCreateView.as_view(),
        name='register'
    ),
    path('board/add/', bv.AddBoardView.as_view(), name='add_board'),
    path(
        'board/<slug:slug>/thread/add/',
        bv.AddThreadView.as_view(),
        name='add_thread'
    ),
    path('board/<slug:slug>/', bv.BoardView.as_view(), name='board'),
    path('thread/<slug:slug>/', bv.ThreadView.as_view(), name='thread'),
    path(
        'thread/<slug:slug>/change_status/',
        bv.change_thread_status,
        name='change_thread_status'
    ),
    path('thread/<slug:slug>/post/add/', bv.PostView.as_view(), name='post'),
    path('<slug:slug>/', bv.ProfileView.as_view(), name='profile'),
    path(
        '<slug:slug>/change_person_status/',
        bv.change_person_status,
        name='change_person_status'
    ),
    path(
        '<slug:slug>/change_role/<int:role>/',
        bv.change_role,
        name='change_role'
    ),
]

base/bulletin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

user_roles = [
    "Poster",
    "Moderator",
    "Administrator",
]
user_role_selection = [(i+1, user_roles[i]) for i in range(len(user_roles))]


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.IntegerField(default=1, choices=user_role_selection)
    is_banned = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.slug


class Board(models.Model):
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(Person, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    position = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_thread_with_latest_reply(self):
        threads = self.thread_set.all()
        count = threads.count()
        if count > 0:
            latest_date, index = threads[0].get_latest_reply_date(), 0
            for i in range(1, threads.count()):
                curr_date = threads[i].get_latest_reply_date()
                if not latest_date or curr_date and curr_date > latest_date:
                    latest_date = curr_date
                    index = i
            return threads[index]

    def post_count(self):
        threads = self.thread_set.all()
        count = 0
        for thread in threads:
            count += thread.post_set.count()
        return count


class Thread(models.Model):
    title = models.CharField(max_length=100)
    posted_by = models.ForeignKey(Person, on_delete=models.CASCADE)
    posted_on = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    is_locked = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.slug

    def get_latest_reply(self):
        if self.post_set.count() > 0:
            return self.post_set.order_by('-posted_on')[0]

    def get_latest_reply_date(self):
        reply = self.get_latest_reply()
        if reply:
            return reply.posted_on


class Post(models.Model):
    message = models.TextField()
    posted_by = models.ForeignKey(Person, on_delete=models.CASCADE)
    posted_on = models.DateTimeField(auto_now_add=True)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)

    def __str__(self):
        return self.message


User._meta.get_field('last_name').blank = False
User._meta.get_field('last_name').null = False
User._meta.get_field('first_name').blank = False
User._meta.get_field('first_name').null = False

base/bulletin/forms.py
from django.contrib.auth import models as am, forms as af

from bulletin import models as bm


class RegisterForm(af.UserCreationForm):
    class Meta:
        model = am.User
        fields = ('username', 'last_name', 'first_name', 'email')

    def save(self):
        user = super().save()
        bm.Person.objects.create(user=user)
        return user

base/bulletin/views.py
from django.contrib import messages as msg
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView

from bulletin import models as bm, forms as bf


class PasswordUpdateView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'bulletin/form.html'
    success_url = reverse_lazy('bulletin:index')
    success_message = 'Password Changed!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Change Password'
        return context


class UserCreateView(SuccessMessageMixin, CreateView):
    template_name = 'bulletin/form.html'
    success_url = reverse_lazy('bulletin:index')
    success_message = 'User Created!'
    form_class = bf.RegisterForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create User'
        return context


class IndexView(ListView):
    context_object_name = 'boards'
    template_name = 'bulletin/index.html'
    paginate_by = 20

    def get_queryset(self):
        return bm.Board.objects.all().order_by('-position')


class BoardView(SingleObjectMixin, ListView):
    template_name = 'bulletin/board.html'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=bm.Board.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["board"] = self.object
        return context

    def get_queryset(self):
        return self.object.thread_set.order_by('-posted_on')


class ThreadView(SingleObjectMixin, ListView):
    template_name = 'bulletin/thread.html'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=bm.Thread.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["thread"] = self.object
        return context

    def get_queryset(self):
        return self.object.post_set.order_by('posted_on')


def role_test(self, level):
    if self.person.role >= bm.user_roles.index(level) + 1:
        return True
    raise Http404()


def administrator_test(self):
    return role_test(self, "Administrator")


def moderator_test(self):
    return role_test(self, "Moderator")


class AdministratorTestMixin(UserPassesTestMixin):
    def test_func(self):
        return administrator_test(self.request.user)


class ModeratorTestMixin(UserPassesTestMixin):
    def test_func(self):
        return moderator_test(self.request.user)


class AddBoardView(AdministratorTestMixin, CreateView):
    template_name = 'bulletin/form.html'
    success_url = reverse_lazy('bulletin:index')
    model = bm.Board
    fields = ('name', 'position')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Board'
        return context

    def form_valid(self, form):
        board = form.save(commit=False)
        board.creator = self.request.user.person
        try:
            board.save()
            msg.info(self.request, 'Board added!')
        except IntegrityError:
            msg.error(
                self.request,
                'Board cannot be created due to name conflict!'
            )
            return redirect(self.get_success_url())
        return super().form_valid(form)


class AddThreadView(ModeratorTestMixin, CreateView):
    template_name = 'bulletin/form.html'
    model = bm.Thread
    fields = ('title',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Thread'
        return context

    def form_valid(self, form):
        thread = form.save(commit=False)
        thread.posted_by = self.request.user.person
        thread.board = bm.Board.objects.get(slug=self.kwargs['slug'])
        try:
            thread.save()
            msg.info(self.request, 'Thread added!')
        except IntegrityError:
            msg.error(
                self.request,
                'Thread cannot be created due to title conflict!'
            )
            return redirect(self.get_success_url())
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('bulletin:board', args=(self.kwargs['slug'],))


class PostView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'bulletin/form.html'
    success_message = 'Post Added!'
    model = bm.Post
    fields = ('message',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add Post'
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.posted_by = self.request.user.person
        post.thread = bm.Thread.objects.get(slug=self.kwargs['slug'])
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('bulletin:thread', args=(self.kwargs['slug'],))


class ProfileView(SingleObjectMixin, ListView):
    model = bm.Person
    template_name = 'bulletin/profile.html'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=bm.Person.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["person"] = self.object
        return context

    def get_queryset(self):
        return self.object.post_set.order_by('-posted_on')


@login_required
@user_passes_test(moderator_test)
def change_thread_status(request, slug):
    thread = bm.Thread.objects.get(slug=slug)
    thread.is_locked = not thread.is_locked
    if thread.is_locked:
        msg.error(request, 'Thread locked!')
    else:
        msg.info(request, 'Thread unlocked!')
    thread.save()
    return redirect(reverse('bulletin:thread', args=(slug,)))


@login_required
@user_passes_test(moderator_test)
def change_person_status(request, slug):
    person = bm.Person.objects.get(slug=slug)
    person.is_banned = not person.is_banned
    if person.is_banned:
        msg.error(request, 'Person banned!')
    else:
        msg.info(request, 'Person unbanned!')
    person.save()
    return redirect(reverse('bulletin:profile', args=(slug,)))


@login_required
@user_passes_test(administrator_test)
def change_role(request, slug, role):
    person = bm.Person.objects.get(slug=slug)
    person.role = role
    person.save()
    msg.warning(request, 'User role changed!')
    return redirect(reverse('bulletin:profile', args=(slug,)))

base/bulletin/templates/bulletin/board.html
{% extends 'base.html' %}

{% block title %}Bulletin Board{% endblock %}

{% block nav %}
    {% if user.person.role > 1 and not user.person.is_banned %}
        <a class="nav-item nav-link" href="{% url 'bulletin:add_thread' board.slug %}">Add Thread</a>
    {% endif %}
{% endblock %}

{% block content %}
<div class="container row py-2">
    <div class="col">
        <h3>{{ board.name }}</h3>
        <ul>
            <li>Creator: <a href="{% url 'bulletin:profile' board.creator.slug %}">{{ board.creator }}</a></li>
            <li>Date: {{ board.created_on }}</li>
        </ul>
        <h4>Threads</h4>
        <ul>
            {% for thread in page_obj %}
                <li>
                    <a href="{% url 'bulletin:thread' thread.slug %}">{{ thread.title }}{% if thread.is_locked %}(Locked){% endif %}</a>   
                    <ul>
                        <li> <a href="{% url 'bulletin:profile' thread.posted_by.slug %}">{{ thread.posted_by }}</a></li>
                        <li>{{ thread.posted_on }}</li>
                        {% if thread.get_latest_reply %}
                            {% with reply=thread.get_latest_reply %}
                                <li>Last Reply: <a href="{% url 'bulletin:profile' reply.posted_by.slug %}">{{ reply.posted_by }}</a> - {{ reply.posted_on }}</li>
                            {% endwith %}
                        {% else %}
                            <li>No posts yet!</li>
                        {% endif %}
                    </ul>
                </li>
            {% empty %}
                <li>No threads yet!</li>
            {% endfor %}
        </ul>
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

base/bulletin/templates/bulletin/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class='col-md-3'></div>
    <div class='col-md-6 py-2'>
        <h2 class='bg-info p-2 rounded-top text-light mb-0'>{{ title }}</h2>
        <form method="POST" class="bg-light p-2">
            {% csrf_token %}
            {{ form|crispy }}
            <button class='btn btn-primary'>Submit</button>
        </form>
    </div>
    <div class='col-md-3'></div>
</div>
{% endblock %}

base/bulletin/templates/bulletin/index.html
{% extends 'base.html' %}

{% block title %}Bulletin Board{% endblock %}

{% block nav %}
    {% if user.person.role > 2 and not user.person.is_banned %}
        <a class="nav-item nav-link" href="{% url 'bulletin:add_board' %}">Add Board</a>
    {% endif %}
{% endblock %}

{% block content %}
<div class="container row py-2">
    <div class="col">
        <h3>Boards</h3>
        <ul>
            {% for board in boards %}
                <li>
                    <a href="{% url 'bulletin:board' board.slug %}">{{ board.name }}</a>   
                    <ul>
                        <li>Creator: <a href="{% url 'bulletin:profile' board.creator.slug %}">{{ board.creator }}</a></li>
                        <li>Created on: {{ board.created_on }}</li>
                        {% if board.get_thread_with_latest_reply %}
                            {% with th=board.get_thread_with_latest_reply %}
                                <li><a href="{% url 'bulletin:thread' th.slug %}"></a>Recent Active Thread: {{ th.title }}</li>
                            {% endwith %}
                        {% else %}
                            <li>No Threads Yet</li>
                        {% endif %}
                        {% if board.thread_set.count > 0 %}
                            <li>Thread Count: {{ board.thread_set.count }}</li>
                        {% endif %}
                        {% if board.post_count > 0 %}
                            <li>Post Count: {{ board.post_count }}</li>
                        {% endif %}
                    </ul>
                </li>
            {% empty %}
                <li>No boards yet!</li>
            {% endfor %}
        </ul>
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

base/bulletin/templates/bulletin/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="d-md-flex align-items-center flex-column justify-content-center h-100">
    <div>
        <h2 class='bg-info p-2 rounded-top text-light mb-0'>Login</h2>
        <form method="POST" class="bg-light p-2">
            <fieldset>
                {% csrf_token %}
                {{ form|crispy }}
                <button class='btn btn-info'>Submit</button>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

base/bulletin/templates/bulletin/profile.html
{% extends 'base.html' %}

{% block title %}Bulletin Board{% endblock %}

{% block content %}
<div class="container row py-2">
    <div class="col">
        <h3>{{ person.user.get_full_name }}</h3>
        {% if user.is_authenticated and user.person != person %}
            Action:
            {% if user.person.role > 1 and not user.person.is_banned %}
                {% if person.is_banned %}
                    <a href="{% url 'bulletin:change_person_status' person.slug %}" class="btn btn-primary">Unban Person</a>
                {% else %}
                     <a href="{% url 'bulletin:change_person_status' person.slug %}" class="btn btn-danger">Ban Person</a>
                {% endif %}
            {% endif %}
            {% if user.person.role > 2 and not user.person.is_banned %}
                {% if person.role != 1 %}
                    <a href="{% url 'bulletin:change_role' person.slug 1 %}" class='btn btn-warning'>Assign as Poster</a>
                {% endif %}
                {% if person.role != 2 %}
                    <a href="{% url 'bulletin:change_role' person.slug 2 %}" class='btn btn-warning'>Assign as Moderator</a>
                {% endif %}
                {% if person.role != 3 %}
                    <a href="{% url 'bulletin:change_role' person.slug 3 %}" class='btn btn-warning'>Assign as Administrator</a>
                {% endif %}
            {% endif %}
        {% endif %}
        <h4>Posts</h4>
        {% if page_obj %}
            <dl>
                {% for post in page_obj %}
                    <dt> <a href="{% url 'bulletin:thread' post.thread.slug %}">{{ post.thread }}</a> - {{ post.posted_on }}</dt>
                    <dd>{{ post.message }}</dd>
                {% endfor %}
            </dl>
        {% else %}
            <p>No posts yet!</p>
        {% endif %}
        </dl>
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

base/bulletin/templates/bulletin/reply.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary">Reply</button>
</form>
{% endblock %}

base/bulletin/templates/bulletin/thread.html
{% extends 'base.html' %}

{% block title %}Bulletin Board{% endblock %}

{% block nav %}
    {% if not user.person.is_banned %}
        {% if not thread.is_locked %}
            <a class="nav-item nav-link" href="{% url 'bulletin:post' thread.slug %}">Add Post</a>
        {% endif %}
        {% if user.person.role > 1 %}
            <a class="nav-item nav-link" href="{% url 'bulletin:change_thread_status' thread.slug %}">
                {% if thread.is_locked %}
                    Unlock Thread
                {% else %}
                    Lock Thread
                {% endif %}
            </a>
        {% endif %}    
    {% endif %}
{% endblock %}

{% block content %}
<div class="container row py-2">
    <div class="col">
        <h3>{{ thread.title }} {% if thread.is_locked %}(Locked){% endif %}</h3>
        <h5>Board: {{ thread.board.name }}</h5>
        <ul>
            <li>Author:  <a href="{% url 'bulletin:profile' thread.posted_by.slug %}">{{ thread.posted_by }}</a></li>
            <li>Date: {{ thread.posted_on }}</li>
        </ul>
        <h4>Posts</h4>
        {% if page_obj %}
            <dl>
                {% for post in page_obj %}
                    <dt> <a href="{% url 'bulletin:profile' post.posted_by.slug %}">{{ post.posted_by }}</a> - {{ post.posted_on }}</dt>
                    <dd>{{ post.message }}</dd>
                {% endfor %}
            </dl>
        {% else %}
            <p>No posts yet!</p>
        {% endif %}
        </dl>
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}